<?php
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../middleware/auth.php';
require_once __DIR__ . '/../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

require_auth(['admin']);

$type = $_GET['type'] ?? '';
$html = '';
$filename = 'report.pdf';
$title = 'Report';

// Base CSS for PDF
$css = '
    body { font-family: Helvetica, Arial, sans-serif; font-size: 14px; color: #333; }
    .header { text-align: center; border-bottom: 2px solid #e11d48; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { margin: 0; color: #0f172a; font-size: 24px; text-transform: uppercase; }
    .header p { margin: 5px 0 0; color: #64748b; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th, td { border: 1px solid #cbd5e1; padding: 10px; text-align: left; }
    th { background-color: #f8fafc; color: #0f172a; font-weight: bold; text-transform: uppercase; font-size: 12px; }
    .text-right { text-align: right; }
    .footer { position: fixed; bottom: -30px; left: 0px; right: 0px; height: 30px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #cbd5e1; padding-top: 10px; }
';

$head = '<style>' . $css . '</style>';
$letterhead = '
    <div class="header">
        <h1>Department Management System</h1>
        <p>Official Academic & Financial Report</p>
        <p>Generated on: ' . date('F j, Y, g:i a') . '</p>
    </div>
';
$footer = '<div class="footer">Confidential Internal Document - Generated by DMS Reporting Engine</div>';

if ($type === 'student_list') {
    $filename = 'student_roster_' . date('Y-m-d') . '.pdf';
    $title = 'Student Roster';
    
    $stmt = $pdo->query('
        SELECT users.name, users.email, students.matric_no, students.level 
        FROM users 
        INNER JOIN students ON students.user_id = users.id 
        WHERE users.role_id = (SELECT id FROM roles WHERE slug = "student")
        ORDER BY students.level, users.name
    ');
    $students = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    $table = '<table><thead><tr><th>Name</th><th>Matric Number</th><th>Level</th><th>Email</th></tr></thead><tbody>';
    foreach ($students as $s) {
        $table .= '<tr><td>' . e($s['name']) . '</td><td>' . e($s['matric_no']) . '</td><td>' . e($s['level']) . '</td><td>' . e($s['email']) . '</td></tr>';
    }
    $table .= '</tbody></table>';
    
    $html = '<html><head>' . $head . '<title>' . $title . '</title></head><body>' . $letterhead . '<h2>' . $title . '</h2>' . $table . $footer . '</body></html>';

} elseif ($type === 'staff_list') {
    $filename = 'staff_directory_' . date('Y-m-d') . '.pdf';
    $title = 'Staff Directory';
    
    $stmt = $pdo->query('
        SELECT users.name, users.email, staff.designation, staff.office 
        FROM users 
        INNER JOIN staff ON staff.user_id = users.id 
        WHERE users.role_id = (SELECT id FROM roles WHERE slug = "staff")
        ORDER BY staff.designation, users.name
    ');
    $staff = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    $table = '<table><thead><tr><th>Name</th><th>Designation</th><th>Office</th><th>Email</th></tr></thead><tbody>';
    foreach ($staff as $s) {
        $table .= '<tr><td>' . e($s['name']) . '</td><td>' . e($s['designation']) . '</td><td>' . e($s['office']) . '</td><td>' . e($s['email']) . '</td></tr>';
    }
    $table .= '</tbody></table>';
    
    $html = '<html><head>' . $head . '<title>' . $title . '</title></head><body>' . $letterhead . '<h2>' . $title . '</h2>' . $table . $footer . '</body></html>';

} elseif ($type === 'financial_ledger') {
    $filename = 'financial_ledger_' . date('Y-m-d') . '.pdf';
    $title = 'Financial Ledger';
    
    // Revenue
    $revStmt = $pdo->query('SELECT SUM(amount) FROM payments WHERE status = "paid"');
    $totalRevenue = (float)$revStmt->fetchColumn();
    
    // Expenses
    $expStmt = $pdo->query('SELECT SUM(amount) FROM expenses');
    $totalExpenses = (float)$expStmt->fetchColumn();
    
    $netBalance = $totalRevenue - $totalExpenses;
    
    $summary = '
        <table style="width: 50%; margin-bottom: 40px;">
            <tr><th>Total Revenue</th><td class="text-right">' . money($totalRevenue) . '</td></tr>
            <tr><th>Total Expenses</th><td class="text-right">' . money($totalExpenses) . '</td></tr>
            <tr><th>Net Balance</th><td class="text-right"><strong>' . money($netBalance) . '</strong></td></tr>
        </table>
    ';
    
    $html = '<html><head>' . $head . '<title>' . $title . '</title></head><body>' . $letterhead . '<h2>' . $title . ' Summary</h2>' . $summary . $footer . '</body></html>';

} elseif ($type === 'timetable') {
    $levelFilter = $_GET['level'] ?? 'Full';
    $filename = 'timetable_' . strtolower($levelFilter) . '_' . date('Y-m-d') . '.pdf';
    $title = 'Departmental Timetable (' . htmlspecialchars($levelFilter) . ')';
    
    $query = 'SELECT timetable.*, courses.code, users.name AS lecturer 
              FROM timetable 
              INNER JOIN courses ON courses.id = timetable.course_id 
              LEFT JOIN staff ON staff.id = timetable.staff_id 
              LEFT JOIN users ON users.id = staff.user_id ';
    $params = [];
    
    if ($levelFilter !== 'Full') {
        $query .= ' WHERE timetable.level = ? ';
        $params[] = $levelFilter;
    }
    $query .= ' ORDER BY FIELD(day_of_week, "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"), start_time';
    
    $stmt = $pdo->prepare($query);
    $stmt->execute($params);
    $slots = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    $days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    $groupedSlots = [];
    foreach ($days as $day) {
        $groupedSlots[$day] = [];
    }
    foreach ($slots as $s) {
        if (isset($groupedSlots[$s['day_of_week']])) {
            $groupedSlots[$s['day_of_week']][] = $s;
        }
    }
    
    $html = '<html><head>' . $head . '<title>' . $title . '</title></head><body>' . $letterhead . '<h2>' . $title . '</h2>';
    
    $hasSlots = false;
    foreach ($days as $day) {
        if (!empty($groupedSlots[$day])) {
            $hasSlots = true;
            $html .= '<h3 style="background-color: #f1f5f9; padding: 8px; margin-top: 20px; font-size: 14px; text-transform: uppercase;">' . $day . '</h3>';
            $html .= '<table><thead><tr><th>Time</th><th>Course</th><th>Level</th><th>Venue</th><th>Lecturer</th></tr></thead><tbody>';
            foreach ($groupedSlots[$day] as $slot) {
                $timeStr = substr($slot['start_time'], 0, 5) . ' - ' . substr($slot['end_time'], 0, 5);
                $html .= '<tr><td>' . $timeStr . '</td><td>' . e($slot['code']) . '</td><td>' . e($slot['level']) . '</td><td>' . e($slot['venue']) . '</td><td>' . e($slot['lecturer'] ?? 'Unassigned') . '</td></tr>';
            }
            $html .= '</tbody></table>';
        }
    }
    
    if (!$hasSlots) {
        $html .= '<p>No classes scheduled for ' . htmlspecialchars($levelFilter) . '.</p>';
    }
    
    $html .= $footer . '</body></html>';

} else {
    die("Invalid report type.");
}

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream($filename, ["Attachment" => true]);
